---
title: "Bibi_MixedEffectModel_Oct312022"
author: "Jonathan Farr"
date: '2022-11-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 ## Reading in packages

```{r}
library(tidyverse)
library(raster) # reading in raster files
library(sf) # for reading in shapefiles 
library(lme4)
library(sp)
library(ggplot2)
library(ordinal)
```

Averaging raster values from maxent mods to get average HSI value
```{r}
Bison_HSI = raster("/Final_Models_Sept202022//M_0.1_F_lqp_Set_1/Bison_avg.asc")
crs(Bison_HSI) = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

```




# reading in journal observation points
```{r}
setwd("your_directory")

JObs.df = read.csv("Journal_Obs_Final_June7_JJF.csv") %>% # read in CSV
  dplyr::select(-c("Remarks", "Remark2", "Remarks3")) %>%
  mutate(BIBI_Ab = BIBI.herd+ BIBI.sign+ BIBI.kill, 
         BIBI_Pres=  ifelse(BIBI_Ab > 0, 1, 0), 
         Others_Pres = ifelse(Others > 0, 1, 0), 
         BIBI_Ab_categories =  cut(BIBI_Ab, breaks = c(-1,0,5,10,15, Inf)), 
         Others_categories = cut(Others, breaks = c(-1,0,3,20)), # categories for human abundance
         Wolf_Ab = CALU.sign + CALU.pack + CALU.kill, 
         Wolf_Cat = cut(Wolf_Ab, breaks = c(-1, 0, 5, 10, 15, Inf)), #categories for wolf abundance
         Griz_Ab = URAR.sign + URAR.kill + URAR.herd, 
         Griz_Cat = cut(Griz_Ab, breaks = c(-1, 0, 5, 10, 15, Inf))) %>% # categories for bear abundance
  filter(Wdat != "nd",  Ldat !="nd")

#change CSV to simple feature
JObs.sf = st_as_sf(x = JObs.df,  coords = c("X", "Y"),
                  crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" ) # set coords

# extract raster values to points
JObs.sf$bisonHSI = raster::extract(Bison_HSI, JObs.sf)

JObs.sf = subset(JObs.sf, bisonHSI != "NA")

JObs = data.frame(JObs.sf) %>% dplyr::select(-c("geometry")) 

str(JObs)
```


Brief summary statistics for results
```{r}
count(JObs, BIBI_Pres) # bison records
count(JObs, BIBI.sign) # bison sign vs sightings


count(JObs, Others)

count(JObs, CALU.sign)

count(JObs, URAR.sign)

hist(subset(JObs, BIBI_Ab != 0)$BIBI_Ab)
```

Fitting models for presence/absence
```{r}
JObs.mod.data = JObs %>% 
  na.omit(Wolf_Ab) %>% 
  mutate(Griz_Ab_scaled = scale(Griz_Ab), # center and scale continuous variables
         Wolf_Ab_scaled = scale(Wolf_Ab),    
         Others_scaled = scale(Others),
         bisonHSI_scaled = scale(bisonHSI), 
         BIBI_Ab_categories = as.ordered(factor(BIBI_Ab_categories, 
                                                labels=c("None", "Low", "Moderate", "High", "Very High")))) %>% 
  dplyr::select(BIBI_Ab, BIBI_Pres, BIBI_Ab_categories,Observer, Griz_Ab_scaled, Wolf_Ab_scaled, Others_scaled, bisonHSI_scaled)

str(JObs.mod.data)

# predictor variables: 
# - bison habitat suitability (scaled; accounts for differences caused by bottom up effects)
# - human, wolf and grizzly bear abundance (scaled and centered, top-down effects)
# - random effect: journalist (account for differences caused by temporal differences or observer differences)

# checking correlations between predictors, are any R values > 0.6? 
Hmisc::rcorr(as.matrix(JObs.mod.data[,c("Griz_Ab_scaled", "Wolf_Ab_scaled", "Others_scaled","bisonHSI_scaled" )]))

# bison presence/absence model
BIBI_Pres_mod = glmer(BIBI_Pres ~ bisonHSI_scaled + Others_scaled + Griz_Ab_scaled + Wolf_Ab_scaled +
                                     (1|Observer), family = binomial(link = "logit"), data = JObs.mod.data, na.action = "na.fail")

BIBI_Pres_dredge = MuMIn::dredge(BIBI_Pres_mod) # the top model includes all predictors

# looking at model outputs
summary(BIBI_Pres_mod) 
# calculate marginal and conditional R2 values to evaluate how much of the variation is explained by fixed/random effects
performance::r2(BIBI_Pres_mod)
```